import 'package:json_annotation/json_annotation.dart';

part 'action_proposal.g.dart';

/// A structured action proposal for human review and approval.
///
/// Generated by Behavior 4 (Action Proposal) of the Qwen Autopilot agent.
/// `requiresApproval` is always `true` per SOC 2 CC6.8.3 and the
/// Change Management Policy.
@JsonSerializable(explicitToJson: true)
class ActionProposal {
  /// Why this action is needed.
  final String reasoning;

  /// The response policy ID to execute.
  final String recommendedPolicyId;

  /// What will change if this action is executed.
  final String expectedEffects;

  /// How to undo the action if it causes issues.
  final String rollbackPlan;

  /// Risk level of the proposed action (LOW, MEDIUM, HIGH).
  final String riskLevel;

  /// Whether human approval is required (always true).
  final bool requiresApproval;

  /// Compliance controls that mandate this approval gate.
  final List<String> complianceControls;

  /// The event ID this proposal is associated with.
  final String? eventId;

  /// Whether the proposal targets a trusted network IP.
  final bool trustedNetworkMatch;

  const ActionProposal({
    required this.reasoning,
    required this.recommendedPolicyId,
    required this.expectedEffects,
    required this.rollbackPlan,
    required this.riskLevel,
    this.requiresApproval = true,
    this.complianceControls = const [],
    this.eventId,
    this.trustedNetworkMatch = false,
  });

  factory ActionProposal.fromJson(Map<String, dynamic> json) =>
      _$ActionProposalFromJson(json);

  Map<String, dynamic> toJson() => _$ActionProposalToJson(this);
}
