#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# sample-attack-traffic.sh
#
# Auto-generated by generate-trusted-networks.sh — do not edit manually.
# Regenerate: skills/blueteam-autopilot-prep/scripts/generate-trusted-networks.sh
#
# Sends sample WAF attack traffic to: ecs.muayid.com
# Region: ap-southeast-1
# Generated: 2026-07-09T19:17:56Z
#
# Prerequisites:
#   - aliyun CLI installed and configured (credentials in .env or shell)
#   - WAF protection mode set to Block (not Observe)
# =============================================================================

TEST_DOMAIN="ecs.muayid.com"
ALIBABA_REGION="ap-southeast-1"
# Auto-discover account ID via STS if not already set
if [ -z "${ACCOUNT_ID:-}" ] || [ "${ACCOUNT_ID}" = "YOUR_ACCOUNT_ID" ]; then
  ACCOUNT_ID=$(aliyun sts GetCallerIdentity 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('AccountId',''))" 2>/dev/null || echo "")
  if [ -z "$ACCOUNT_ID" ]; then
    echo "Error: Could not discover ACCOUNT_ID via 'aliyun sts GetCallerIdentity'."
    echo "       Export it manually: export ACCOUNT_ID=<your-account-id>"
    exit 1
  fi
fi

echo "=== BlueTeam: Sample Attack Traffic ==="
echo ""
echo "Target domain: ${TEST_DOMAIN}"
echo "Region: ${ALIBABA_REGION}"
echo ""

echo "--- SQL Injection Probe ---"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -g   "http://${TEST_DOMAIN}/?id=1%27%20OR%20%271%27%3D%271")
echo "HTTP ${HTTP_CODE} (expected: 405 — blocked by WAF)"
echo ""

echo "--- XSS Probe ---"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -g   "http://${TEST_DOMAIN}/search?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E")
echo "HTTP ${HTTP_CODE} (expected: 405 — blocked by WAF)"
echo ""

echo "--- Path Traversal Probe ---"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -g   "http://${TEST_DOMAIN}/download?file=..%2F..%2Fetc%2Fpasswd")
echo "HTTP ${HTTP_CODE} (expected: 405 — blocked by WAF)"
echo ""

echo "--- Normal Traffic (should pass) ---"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -g   "http://${TEST_DOMAIN}/")
echo "HTTP ${HTTP_CODE} (expected: 200 — normal page served)"
echo ""

echo "=== Traffic sent. Waiting 30s for log propagation... ==="
sleep 30

echo ""
echo "=== Verify logs in SLS ==="
FROM_TS=$(date -u -v-10M +%s 2>/dev/null || date -u -d '10 minutes ago' +%s)
TO_TS=$(date -u +%s)
aliyun sls GetLogs \
  --project "wafnew-project-${ACCOUNT_ID}-${ALIBABA_REGION}" \
  --logstore "wafnew-logstore" \
  --from "${FROM_TS}" \
  --to "${TO_TS}" \
  --query "matched_host: ${TEST_DOMAIN}-waf | SELECT final_action, final_plugin, final_rule_type LIMIT 5" \
  --region "${ALIBABA_REGION}" 2>&1 | head -40
echo ""
echo "Expected: Log entries with final_action: block"
