// Generated MCP stdio server
// DO NOT EDIT - automatically generated by mcp_generator

import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;


import 'package:dart_mcp/server.dart';
import 'package:dart_mcp/stdio.dart';



import 'package:alibaba_security_mcp/src/alibaba_security_server.dart' as alibaba_security_server;

Future<void> main() async {
  final server = MCPServerWithTools(
    stdioChannel(input: io.stdin, output: io.stdout),
  );
  await server.done;
}

base class MCPServerWithTools extends MCPServer with ToolsSupport {
  static const bool _logErrors = false;

  MCPServerWithTools(super.channel)
    : super.fromStreamChannel(
        implementation: Implementation(
          name: 'mcp-server',
          version: '1.0.0',
        ),
        instructions: 'Auto-generated MCP server',
      ) {
    registerTool(
      Tool(
        name: 'ping',
        description: 'Health check for the Alibaba Security MCP server. Returns server status, configured region, and execution mode.',
        inputSchema: Schema.object(),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _ping,
    );
    registerTool(
      Tool(
        name: 'list_security_events',
        description: 'List security events from Alibaba Cloud Agentic SOC. Events are higher-level incidents that may aggregate multiple alerts from different sources (WAF, CWPP, Cloud Firewall, etc.). Returns events with IDs, severity, affected assets, and timestamps.',
        inputSchema: Schema.object(
    properties: {
      'timeRange': Schema.string(
      title: 'Time Range Shortcut',
      description: 'Pre-baked time window shortcut. Dart computes exact boundaries. Options: last15Min, lastHour, last4Hours, last24Hours, last7Days, last30Days. Ignored if startIso and endIso are provided.',
      enum: ['last15Min', 'lastHour', 'last4Hours', 'last24Hours', 'last7Days', 'last30Days', 'custom']
    ),
      'startIso': Schema.string(
      title: 'Start Time (ISO 8601)',
      description: 'Custom start time in ISO 8601 format (e.g., 2026-06-11T00:00:00Z). Only used when timeRange is "custom" or not provided.'
    ),
      'endIso': Schema.string(
      title: 'End Time (ISO 8601)',
      description: 'Custom end time in ISO 8601 format (e.g., 2026-06-12T00:00:00Z). Only used when timeRange is "custom" or not provided.'
    ),
      'minSeverity': Schema.string(
      title: 'Minimum Severity',
      description: 'Minimum severity filter. Only events at or above this level are returned.',
      enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
    ),
      'status': Schema.string(
      title: 'Status',
      description: 'Filter events by their investigation status.',
      enum: ['NEW', 'IN_PROGRESS', 'RESOLVED']
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listSecurityEvents,
    );
    registerTool(
      Tool(
        name: 'get_security_event_detail',
        description: 'Get full details of a security event including attack chain stages, source product, attacker IPs, related alerts, and associated vulnerabilities. Wraps the GetAttackEventDetail API.',
        inputSchema: Schema.object(
    properties: {
      'eventId': Schema.string(
      title: 'Event ID',
      description: 'The unique identifier of the security event.'
    ),
    },
    required: ['eventId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _getSecurityEventDetail,
    );
    registerTool(
      Tool(
        name: 'list_alerts_for_event',
        description: 'Retrieve the underlying alerts for a security event, grouped by data source (e.g., WAF, SecurityCenter, CWPP, Cloud Firewall). Each alert includes its ID, rule ID, severity, and message.',
        inputSchema: Schema.object(
    properties: {
      'eventId': Schema.string(
      title: 'Event ID',
      description: 'The security event ID to retrieve alerts for.'
    ),
    },
    required: ['eventId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listAlertsForEvent,
    );
    registerTool(
      Tool(
        name: 'list_vulnerabilities',
        description: 'List vulnerabilities detected on cloud assets by Alibaba Cloud Security Center. Supports filtering by severity, asset, and vulnerability type. Wraps the DescribeVulList API.',
        inputSchema: Schema.object(
    properties: {
      'severity': Schema.string(
      title: 'Severity',
      description: 'Filter by vulnerability severity level.',
      enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
    ),
      'assetId': Schema.string(
      title: 'Asset ID',
      description: 'Filter by specific asset identifier.'
    ),
      'vulType': Schema.string(
      title: 'Vulnerability Type',
      description: 'Filter by vulnerability type category.',
      enum: ['CVE', 'WEB_CMS', 'APP', 'SYSTEM']
    ),
      'page': Schema.int(
      title: 'Page',
      description: 'Page number for paginated results.',
      min: 1
    ),
      'pageSize': Schema.int(
      title: 'Page Size',
      description: 'Number of results per page.',
      min: 1,
      max: 100
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listVulnerabilities,
    );
    registerTool(
      Tool(
        name: 'get_vulnerability_detail',
        description: 'Get detailed information about a specific vulnerability including CVE identifier, description, affected versions, and remediation advice. Wraps the DescribeVulDetails API.',
        inputSchema: Schema.object(
    properties: {
      'vulId': Schema.string(
      title: 'Vulnerability ID',
      description: 'The unique identifier of the vulnerability.'
    ),
    },
    required: ['vulId'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _getVulnerabilityDetail,
    );
    registerTool(
      Tool(
        name: 'list_response_policies',
        description: 'List automated response policies configured in Agentic SOC. These policies define actions taken in response to security events, such as blocking attacker IPs via WAF or quarantining hosts.',
        inputSchema: Schema.object(
    properties: {
      'scope': Schema.string(
      title: 'Scope',
      description: 'Filter policies by scope. WAF returns only WAF-related policies.',
      enum: ['WAF', 'ALL']
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listResponsePolicies,
    );
    registerTool(
      Tool(
        name: 'execute_response_policy',
        description: 'Execute an Agentic SOC response policy. In dry-run mode, returns what would happen without making any changes. In real mode, actually triggers the policy action (e.g., blocking an IP via WAF). Use with caution in production environments.',
        inputSchema: Schema.object(
    properties: {
      'policyId': Schema.string(
      title: 'Policy ID',
      description: 'The response policy to execute.'
    ),
      'eventId': Schema.string(
      title: 'Event ID',
      description: 'Optional event ID to associate with the policy execution.'
    ),
      'dryRun': Schema.bool(
      title: 'Dry Run',
      description: 'If true, simulate execution without making changes. Defaults to the server SECURITY_CENTER_MODE setting.'
    ),
    },
    required: ['policyId'],
  ),
        annotations: ToolAnnotations(destructiveHint: true, openWorldHint: true),
      ),
      _executeResponsePolicy,
    );
    registerTool(
      Tool(
        name: 'get_account_context',
        description: 'Get account context metadata including the configured region, Security Center edition, whether Agentic SOC is enabled, and the current execution mode. Call this first to establish environmental awareness before querying security data.',
        inputSchema: Schema.object(),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _getAccountContext,
    );
    registerTool(
      Tool(
        name: 'get_waf_instance_info',
        description: 'Discover the WAF (Web Application Firewall) instance in the configured region and return its details including status, edition, features, and limits. This tool auto-discovers the instance ID — no manual configuration needed. Call this first to confirm WAF is provisioned before querying WAF security events.',
        inputSchema: Schema.object(),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _getWafInstanceInfo,
    );
    registerTool(
      Tool(
        name: 'list_waf_security_events',
        description: 'List WAF security event logs — individual attack requests that matched WAF protection rules. Returns detailed attack entries including attack type, source IP, target host, request path, and action taken (block/monitor). \n\nUse the timeRange shortcut for common windows (e.g., "last24Hours") or pass custom startIso/endIso for specific periods. \n\nThis is the primary tool for investigating web application attacks such as SQL injection, XSS, path traversal, and scanner activity.',
        inputSchema: Schema.object(
    properties: {
      'timeRange': Schema.string(
      title: 'Time Range Shortcut',
      description: 'Pre-baked time window shortcut. Dart computes exact boundaries. Options: last15Min, lastHour, last4Hours, last24Hours, last7Days, last30Days. Ignored if startIso and endIso are provided.',
      enum: ['last15Min', 'lastHour', 'last4Hours', 'last24Hours', 'last7Days', 'last30Days', 'custom']
    ),
      'startIso': Schema.string(
      title: 'Start Time (ISO 8601)',
      description: 'Custom start time in ISO 8601 format (e.g., 2026-06-11T00:00:00Z). Only used when timeRange is "custom" or not provided.'
    ),
      'endIso': Schema.string(
      title: 'End Time (ISO 8601)',
      description: 'Custom end time in ISO 8601 format (e.g., 2026-06-12T00:00:00Z). Only used when timeRange is "custom" or not provided.'
    ),
      'pageSize': Schema.int(
      title: 'Page Size',
      description: 'Number of events per page (max 100).',
      min: 1,
      max: 100
    ),
      'page': Schema.int(
      title: 'Page Number',
      description: 'Page number for paginated results.',
      min: 1
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listWafSecurityEvents,
    );
    registerTool(
      Tool(
        name: 'list_waf_top_rules',
        description: 'List the top 10 most frequently triggered WAF protection rules within a time window. Returns rule IDs and hit counts. Useful for identifying which attack patterns are most prevalent.',
        inputSchema: Schema.object(
    properties: {
      'timeRange': Schema.string(
      title: 'Time Range Shortcut',
      description: 'Pre-baked time window shortcut. Options: last15Min, lastHour, last4Hours, last24Hours, last7Days, last30Days.',
      enum: ['last15Min', 'lastHour', 'last4Hours', 'last24Hours', 'last7Days', 'last30Days']
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listWafTopRules,
    );
    registerTool(
      Tool(
        name: 'list_waf_top_ips',
        description: 'List the top 10 source IPs by attack count from WAF logs. Returns IP addresses and their hit counts. Useful for identifying persistent attackers and informing IP blocking decisions.',
        inputSchema: Schema.object(
    properties: {
      'timeRange': Schema.string(
      title: 'Time Range Shortcut',
      description: 'Pre-baked time window shortcut. Options: last15Min, lastHour, last4Hours, last24Hours, last7Days, last30Days.',
      enum: ['last15Min', 'lastHour', 'last4Hours', 'last24Hours', 'last7Days', 'last30Days']
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listWafTopIps,
    );
    registerTool(
      Tool(
        name: 'list_assets',
        description: 'List cloud assets (ECS instances, etc.) registered in Security Center. Returns each asset\'s UUID, instance name, public/private IPs, region, asset type, and OS. Use this to dynamically discover the environment\'s asset inventory instead of relying on hardcoded hostnames. Supports an optional search criteria to filter results.',
        inputSchema: Schema.object(
    properties: {
      'criteria': Schema.string(
      title: 'Search Criteria',
      description: 'Optional search string to filter assets by instance name, IP, or other attributes.'
    ),
      'page': Schema.int(
      title: 'Page',
      description: 'Page number for paginated results.',
      min: 1
    ),
      'pageSize': Schema.int(
      title: 'Page Size',
      description: 'Number of results per page.',
      min: 1,
      max: 100
    ),
    },
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listAssets,
    );
    registerTool(
      Tool(
        name: 'list_knowledge_documents',
        description: 'List all available operational knowledge documents. Returns each document type, title, and source (file or embedded) so the caller can discover what is available before requesting a specific document with get_knowledge_document.',
        inputSchema: Schema.object(),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _listKnowledgeDocuments,
    );
    registerTool(
      Tool(
        name: 'get_knowledge_document',
        description: 'Retrieve an operational knowledge document such as compliance controls (NIST CSF, SOC 2), mitigation runbooks, change management policies, asset inventory, or trusted network definitions. Call this tool when you need compliance context for decision-making or runbook steps for mitigation execution.',
        inputSchema: Schema.object(
    properties: {
      'documentType': Schema.string(
      title: 'Document Type',
      description: 'The knowledge document to retrieve. Options: asset_inventory (network topology), trusted_networks (IP whitelist & escalation rules), compliance_nist (NIST CSF Detect & Respond controls), compliance_soc2 (SOC 2 CC6 Logical Access Controls), runbook_waf_triage (WAF threat triage RUN-SEC-042), policy_change_mgmt (firewall/ACL change approval gates).',
      enum: ['asset_inventory', 'trusted_networks', 'compliance_nist', 'compliance_soc2', 'runbook_waf_triage', 'policy_change_mgmt']
    ),
    },
    required: ['documentType'],
  ),
        annotations: ToolAnnotations(readOnlyHint: true, openWorldHint: true),
      ),
      _getKnowledgeDocument,
    );
  }

  /// Guards against duplicate initialization requests (e.g. from MCP Inspector
  /// which may send `initialize` more than once for HTTP endpoints).
  bool _isInitialized = false;
  InitializeResult? _initializeResult;

  @override
  FutureOr<InitializeResult> initialize(InitializeRequest request) async {
    if (_isInitialized) return _initializeResult!;
    _isInitialized = true;
    final result = await super.initialize(request);
    _initializeResult = result;
    return result;
  }

  FutureOr<CallToolResult> _ping(CallToolRequest request) async {
    try {



      final result = alibaba_security_server.AlibabaSecurityServer().ping();
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] ping: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listSecurityEvents(CallToolRequest request) async {
    try {
    final timeRange = request.arguments?['timeRange'] as String?;
    final startIso = request.arguments?['startIso'] as String?;
    final endIso = request.arguments?['endIso'] as String?;
    final minSeverity = request.arguments?['minSeverity'] as String?;
    final status = request.arguments?['status'] as String?;


      final result = await alibaba_security_server.AlibabaSecurityServer().listSecurityEvents(timeRange: timeRange, startIso: startIso, endIso: endIso, minSeverity: minSeverity, status: status);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_security_events: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getSecurityEventDetail(CallToolRequest request) async {
    try {
    final eventId = request.arguments!['eventId'] as String;


      final result = await alibaba_security_server.AlibabaSecurityServer().getSecurityEventDetail(eventId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] get_security_event_detail: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listAlertsForEvent(CallToolRequest request) async {
    try {
    final eventId = request.arguments!['eventId'] as String;


      final result = await alibaba_security_server.AlibabaSecurityServer().listAlertsForEvent(eventId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_alerts_for_event: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listVulnerabilities(CallToolRequest request) async {
    try {
    final severity = request.arguments?['severity'] as String?;
    final assetId = request.arguments?['assetId'] as String?;
    final vulType = request.arguments?['vulType'] as String?;
    final page = (request.arguments?['page'] as int?) ?? 1;
    final pageSize = (request.arguments?['pageSize'] as int?) ?? 20;


      final result = await alibaba_security_server.AlibabaSecurityServer().listVulnerabilities(severity: severity, assetId: assetId, vulType: vulType, page: page, pageSize: pageSize);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_vulnerabilities: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getVulnerabilityDetail(CallToolRequest request) async {
    try {
    final vulId = request.arguments!['vulId'] as String;


      final result = await alibaba_security_server.AlibabaSecurityServer().getVulnerabilityDetail(vulId);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] get_vulnerability_detail: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listResponsePolicies(CallToolRequest request) async {
    try {
    final scope = (request.arguments?['scope'] as String?) ?? 'ALL';


      final result = await alibaba_security_server.AlibabaSecurityServer().listResponsePolicies(scope: scope);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_response_policies: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _executeResponsePolicy(CallToolRequest request) async {
    try {
    final policyId = request.arguments!['policyId'] as String;
    final eventId = request.arguments?['eventId'] as String?;
    final dryRun = request.arguments?['dryRun'] as bool?;


      final result = await alibaba_security_server.AlibabaSecurityServer().executeResponsePolicy(policyId, eventId: eventId, dryRun: dryRun);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] execute_response_policy: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getAccountContext(CallToolRequest request) async {
    try {



      final result = await alibaba_security_server.AlibabaSecurityServer().getAccountContext();
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] get_account_context: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getWafInstanceInfo(CallToolRequest request) async {
    try {



      final result = await alibaba_security_server.AlibabaSecurityServer().getWafInstanceInfo();
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] get_waf_instance_info: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listWafSecurityEvents(CallToolRequest request) async {
    try {
    final timeRange = request.arguments?['timeRange'] as String?;
    final startIso = request.arguments?['startIso'] as String?;
    final endIso = request.arguments?['endIso'] as String?;
    final pageSize = (request.arguments?['pageSize'] as int?) ?? 20;
    final page = (request.arguments?['page'] as int?) ?? 1;


      final result = await alibaba_security_server.AlibabaSecurityServer().listWafSecurityEvents(timeRange: timeRange, startIso: startIso, endIso: endIso, pageSize: pageSize, page: page);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_waf_security_events: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listWafTopRules(CallToolRequest request) async {
    try {
    final timeRange = request.arguments?['timeRange'] as String?;


      final result = await alibaba_security_server.AlibabaSecurityServer().listWafTopRules(timeRange: timeRange);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_waf_top_rules: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listWafTopIps(CallToolRequest request) async {
    try {
    final timeRange = request.arguments?['timeRange'] as String?;


      final result = await alibaba_security_server.AlibabaSecurityServer().listWafTopIps(timeRange: timeRange);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_waf_top_ips: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listAssets(CallToolRequest request) async {
    try {
    final criteria = request.arguments?['criteria'] as String?;
    final page = (request.arguments?['page'] as int?) ?? 1;
    final pageSize = (request.arguments?['pageSize'] as int?) ?? 20;


      final result = await alibaba_security_server.AlibabaSecurityServer().listAssets(criteria: criteria, page: page, pageSize: pageSize);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_assets: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _listKnowledgeDocuments(CallToolRequest request) async {
    try {



      final result = await alibaba_security_server.AlibabaSecurityServer().listKnowledgeDocuments();
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] list_knowledge_documents: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }
  FutureOr<CallToolResult> _getKnowledgeDocument(CallToolRequest request) async {
    try {
    final documentType = request.arguments!['documentType'] as String;


      final result = await alibaba_security_server.AlibabaSecurityServer().getKnowledgeDocument(documentType: documentType);
      return CallToolResult(
        content: [TextContent(text: _serializeResult(result))],
      );
    } catch (e, st) {
      if (_logErrors) {
        io.stderr.writeln('[easy_api] get_knowledge_document: $e');
        io.stderr.writeln(st);
        await io.stderr.flush();
      }
      return CallToolResult(
        content: [TextContent(text: 'An error occurred while processing the request.')],
        isError: true,
      );
    }
  }





  String _serializeResult(dynamic result) {
    if (result == null) return 'null';
    try {
      if (result is Map) return jsonEncode(result);
      if (result is List) {
        final items = result.map((e) {
          if (e == null) return null;
          if (e is Map) return e;
          final toJson = e.toJson;
          if (toJson != null && toJson is Function) return toJson();
          return e.toString();
        }).where((e) => e != null).toList();
        return jsonEncode(items);
      }
      final toJson = result.toJson;
      if (toJson != null && toJson is Function) return jsonEncode(toJson());
      return result.toString();
    } catch (_) {
      return result.toString();
    }
  }
}
